language: c

env:
  global:
    - RACKET_DIR: '~/racket'
  matrix:
    - RACKET_VERSION: '6.1.1'
    - RACKET_VERSION: '6.2'
    - RACKET_VERSION: '6.2.1'
    - RACKET_VERSION: '6.3'
    - RACKET_VERSION: '6.4'
    - RACKET_VERSION: '6.5'
    - RACKET_VERSION: '6.6'
    - RACKET_VERSION: HEAD

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install --installation --auto --link
      $TRAVIS_BUILD_DIR/namespaced-transformer-doc
      $TRAVIS_BUILD_DIR/namespaced-transformer-lib
  - raco pkg install --installation --auto cover cover-coveralls

script:
  - raco test -ep namespaced-transformer-lib namespaced-transformer-doc
  - raco cover -bf coveralls -d $TRAVIS_BUILD_DIR/coverage -p namespaced-transformer-lib
